"""
fcstd_to_obj.py
---------------
FreeCAD headless helper — converts a .fcstd file to a triangulated Wavefront
OBJ file using FreeCAD's built-in Part and Mesh workbenches.

Usage (called by fcstd_importer.gd via OS.execute):
    FreeCAD.exe --console -- fcstd_to_obj.py <source.fcstd> <output.obj>

FreeCAD 1.x exposes its Python API even in --console mode, so this script
runs inside FreeCAD's embedded CPython interpreter and has full access to the
Part, Mesh, and FreeCAD core modules.

Exit codes:
    0  — success, output OBJ written
    1  — wrong number of arguments
    2  — source file not found
    3  — no solid/shape geometry found in the document
    4  — OBJ write failed
"""

import sys
import os

# ---------------------------------------------------------------------------
# Argument handling
# ---------------------------------------------------------------------------
# FreeCAD passes sys.argv[0] as the script path; our arguments start at [1].

if len(sys.argv) < 3:
    sys.stderr.write(
        "Usage: FreeCAD.exe --console -- fcstd_to_obj.py <source.fcstd> <output.obj>\n"
    )
    sys.exit(1)

source_path = sys.argv[1]
output_path = sys.argv[2]

if not os.path.isfile(source_path):
    sys.stderr.write("fcstd_to_obj.py: source file not found: %s\n" % source_path)
    sys.exit(2)

# ---------------------------------------------------------------------------
# FreeCAD imports (available because we are running inside FreeCAD.exe)
# ---------------------------------------------------------------------------
import FreeCAD
import Part
import Mesh
import MeshPart

# ---------------------------------------------------------------------------
# Load the document
# ---------------------------------------------------------------------------
doc = FreeCAD.openDocument(source_path)

# ---------------------------------------------------------------------------
# Collect all Part::Feature objects that have a valid Shape
# ---------------------------------------------------------------------------
shapes = []
for obj in doc.Objects:
    if hasattr(obj, "Shape") and obj.Shape and not obj.Shape.isNull():
        shapes.append(obj.Shape)

if not shapes:
    sys.stderr.write(
        "fcstd_to_obj.py: no Part geometry found in '%s'.\n" % source_path
    )
    sys.exit(3)

# ---------------------------------------------------------------------------
# Tessellate each shape and accumulate vertices / faces
# ---------------------------------------------------------------------------
# MeshPart.meshFromShape() calls the Netgen/BRep triangulator inside FreeCAD.
# linear_deflection controls triangle density (smaller = finer, slower).

LINEAR_DEFLECTION  = 0.1   # mm; tune via ProjectSettings if needed
ANGULAR_DEFLECTION = 0.523599  # radians (~30°)

all_vertices = []   # list of (x, y, z) tuples
all_faces    = []   # list of (i, j, k) 0-based index tuples

for shape in shapes:
    mesh = MeshPart.meshFromShape(
        Shape=shape,
        LinearDeflection=LINEAR_DEFLECTION,
        AngularDeflection=ANGULAR_DEFLECTION,
        Relative=False,
    )

    base_index = len(all_vertices)

    for point in mesh.Points:
        all_vertices.append((point.x, point.y, point.z))

    for facet in mesh.Facets:
        i0, i1, i2 = facet.PointIndices
        all_faces.append((base_index + i0, base_index + i1, base_index + i2))

# ---------------------------------------------------------------------------
# Write OBJ
# ---------------------------------------------------------------------------
try:
    with open(output_path, "w", encoding="utf-8") as f:
        f.write("# Generated by fcstd_to_obj.py (FreeCAD %s)\n" % FreeCAD.Version()[0])
        f.write("# Source: %s\n\n" % os.path.basename(source_path))

        for x, y, z in all_vertices:
            # FreeCAD uses mm; Godot uses metres — divide by 1000 here so the
            # mesh lands at a reasonable scale.  Remove the /1000 if you want
            # to keep FreeCAD's native millimetre coordinates.
            f.write("v %.6f %.6f %.6f\n" % (x / 1000.0, y / 1000.0, z / 1000.0))

        f.write("\n")

        for i0, i1, i2 in all_faces:
            # OBJ indices are 1-based
            f.write("f %d %d %d\n" % (i0 + 1, i1 + 1, i2 + 1))

except OSError as exc:
    sys.stderr.write("fcstd_to_obj.py: failed to write OBJ: %s\n" % exc)
    sys.exit(4)

sys.stdout.write(
    "fcstd_to_obj.py: wrote %d vertices, %d triangles to '%s'\n"
    % (len(all_vertices), len(all_faces), output_path)
)
sys.exit(0)
